services:
  - type: web
    name: gescrim-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: gescrim-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: gescrim-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: gescrim-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: gescrim-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: gescrim-db
          property: password
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: MAIL_MAILER
        value: resend
      - key: MAIL_FROM_ADDRESS
        value: "onboarding@resend.dev"
      - key: MAIL_FROM_NAME
        value: Teranga GESCRIM
      - key: RESEND_API_KEY
        sync: false
      - key: JWT_TTL
        value: "480"
      - key: JWT_REFRESH_TTL
        value: "20160"
    healthCheckPath: /api/health

databases:
  - name: gescrim-db
    plan: free
    databaseName: gescrim
    user: gescrim_user
